version: 2.1

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy

jobs:
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Install
          command: |
            cd /usr/local/bin
            sudo wget https://releases.hashicorp.com/terraform/0.12.6/terraform_0.12.6_linux_amd64.zip
            sudo unzip terraform_0.12.6_linux_amd64.zip
            terraform --version
      - run:
          name: Build
          command: |
            ls
            sh build.sh
      - run:
          name: Deploy
          command: |
            terraform init
            terraform plan
