version: 2.1

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy-dev:
          context: magine-dev
      - deploy-stg:
          context: magine-stg
          requires:
            - deploy-dev
          filters:
            branches:
              only:
                - master

jobs:
  deploy-dev: 
    machine: true
    steps:
      - apply:
          environment: dev
  deploy-stg: 
    machine: true
    steps:
      - apply:
          environment: stg

commands:
  apply:
    description: Deploy a Magine lambda function
    parameters:
      environment:
        type: string
    steps:
      - checkout
      - run:
          name: Install
          command: |
            cd /usr/local/bin
            sudo wget https://releases.hashicorp.com/terraform/0.12.6/terraform_0.12.6_linux_amd64.zip
            sudo unzip terraform_0.12.6_linux_amd64.zip
            terraform --version

            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - run:
          name: Build
          command: |
            sh build.sh
      - run:
          name: Plan
          command: |
            cd terraform/environments/<< parameters.environment >>
            terraform init
            terraform plan
      - run:
          name: Deploy
          command: |
            cd terraform/environments/<< parameters.environment >>
            terraform init
            terraform apply -auto-approve