version: 2.1

workflows:
  version: 2
  deploy-dev:
    jobs:
      - deploy-dev:
          context: magine-dev
  deploy-qa:
    jobs:
      - approve-qa:
          type: approval
      - deploy-qa:
          context: magine-dev
          requires:
            - approve-qa
  deploy-ppd:
    jobs:
      - deploy-ppd:
          context: magine-dev
          filters:
            branches:
              only:
                - master
                - feature/preproduction-environment
  deploy:
    jobs:
      - approve-stg:
          type: approval
          filters:
            branches:
              only:
                - master
      - deploy-stg:
          context: magine-dev
          requires:
            - approve-stg
      - approve-prd:
          type: approval
          requires:
            - deploy-stg
      - deploy-prd:
          context: magine-dev
          requires:
            - approve-prd

jobs:
  deploy-dev: 
    machine: true
    steps:
      - apply:
          environment: dev
  deploy-qa: 
    machine: true
    steps:
      - apply:
          environment: qa
  deploy-stg: 
    machine: true
    steps:
      - apply:
          environment: stg
  deploy-ppd: 
    machine: true
    steps:
      - apply:
          environment: ppd
  deploy-prd: 
    machine: true
    steps:
      - apply:
          environment: prd

commands:
  apply:
    description: Deploy a Magine lambda function
    parameters:
      environment:
        type: string
    steps:
      - checkout
      - run:
          name: Install
          command: |
            cd /usr/local/bin
            sudo wget https://releases.hashicorp.com/terraform/0.12.6/terraform_0.12.6_linux_amd64.zip
            sudo unzip terraform_0.12.6_linux_amd64.zip
            terraform --version

            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - run:
          name: Build
          command: |
            sh build.sh
      - run:
          name: Plan
          command: |
            cd terraform/environments/<< parameters.environment >>
            terraform init
            terraform plan
      - run:
          name: Deploy
          command: |
            cd terraform/environments/<< parameters.environment >>
            terraform init
            terraform apply -auto-approve
