version: 2.1

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy

jobs:
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build
          command: |
            ls
            sh build.sh
